### ISSUE TITLE
[Bug] Error on connect and disconnect

### ISSUE THREAD

**Issue by anhgelus** [msmp-mc/msmp-core#2]
`org.bukkit.event.EventException: null`

Connect:
```log
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property LOGGER has not been initialized
at world.anhgelus.msmp.msmpcore.PluginBase$CompanionBase.getLOGGER(PluginBase.kt:28) ~[?:?]
at world.anhgelus.msmp.msmpcore.player.MPlayerManager.connectionOfPlayer(MPlayerManager.kt:40) ~[?:?]
at world.anhgelus.msmp.msmpcore.event.MPlayerListener.onPlayerJoin(MPlayerListener.kt:16) ~[?:?]
```

Disconnect:
```log
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property LOGGER has not been initialized
at world.anhgelus.msmp.msmpcore.PluginBase$CompanionBase.getLOGGER(PluginBase.kt:28) ~[?:?]
at world.anhgelus.msmp.msmpcore.player.MPlayer.updateOnlineStatus(MPlayer.kt:104) ~[?:?]
at world.anhgelus.msmp.msmpcore.player.MPlayer.<init>(MPlayer.kt:56) ~[?:?]
at world.anhgelus.msmp.msmpcore.player.MPlayer.<init>(MPlayer.kt) ~[?:?]
at world.anhgelus.msmp.msmpcore.player.MPlayer$Companion.fromPlayer(MPlayer.kt:127) ~[?:?]
at world.anhgelus.msmp.msmpcore.player.MPlayerManager.get(MPlayerManager.kt:30) ~[?:?]
at world.anhgelus.msmp.msmpcore.event.MPlayerListener.onPlayerQuit(MPlayerListener.kt:21) ~[?:?]
```

**Comment by anhgelus** [comment]
Fixed
