### ISSUE TITLE
The LOGGER is not initialized despite the good usage

### ISSUE THREAD

**Issue by Akik4** [msmp-mc/msmp-core#3]
Error :
 ```
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property LOGGER has not been initialized
	at world.anhgelus.msmp.msmpcore.PluginBase$CompanionBase.getLOGGER(PluginBase.kt:28) ~[?:?]
	at world.anhgelus.msmp.msmpcore.player.MPlayer.updateOnlineStatus(MPlayer.kt:104) ~[?:?]
	at world.anhgelus.msmp.msmpcore.player.MPlayer.<init>(MPlayer.kt:56) ~[?:?]
	at world.anhgelus.msmp.msmpcore.player.MPlayer.<init>(MPlayer.kt) ~[?:?]
	at world.anhgelus.msmp.msmpcore.player.MPlayer$Companion.fromPlayer(MPlayer.kt:127) ~[?:?]
	at world.anhgelus.msmp.msmpcore.player.MPlayerManager.get(MPlayerManager.kt:30) ~[?:?]
```

Init in plugin loader : 

``` kotlin
    override fun enable() {
        INSTANCE = this
        LOGGER = logger
        Bukkit.getPluginManager().registerEvents(RegisterListener, this);
    }
```

Event that cause the error during a PlayerInteractAtEntityEvent
``` kotlin
            if(!MPlayerManager.get(player).isAlive()){
                ChatHelper.sendInfoToPlayer(player, "This player is not dead!")
            }
```

**Comment by anhgelus** [comment]
Linked with #2

**Comment by anhgelus** [comment]
Fixed
