### ISSUE TITLE
[Bug] ToDefaultCondition doesn't handle custom attribute for health

### ISSUE THREAD

**Issue by Akik4** [msmp-mc/msmp-core#4]
Function ToDefaultCondition is defined to 20.0 and not to getPlayerAttribute(Attibute_GENERIC_MAX_HEALTH)
```
aused by: java.lang.IllegalArgumentException: Health must be between 0 and 10.0(20.0)
	at org.bukkit.craftbukkit.v1_19_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:117) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at world.anhgelus.msmp.alteredrespawn.api.Stack$deathEvent$1.invoke(Stack.kt:46) ~[?:?]
	at world.anhgelus.msmp.alteredrespawn.api.Stack$deathEvent$1.invoke(Stack.kt:43) ~[?:?]
	at world.anhgelus.msmp.msmpcore.player.MPlayer.died(MPlayer.kt:111) ~[?:?]
	at world.anhgelus.msmp.alteredrespawn.api.Stack.deathEvent(Stack.kt:43) ~[?:?]
	at world.anhgelus.msmp.alteredrespawn.listener.RegisterListener.onDamage(RegisterListener.kt:14) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 36 more
```

**Comment by anhgelus** [comment]
Seems to be not fixed, see [this bug](https://github.com/msmp-mc/altered-respawn/issues/6).

**Comment by anhgelus** [comment]
Fixed
